set_property PACKAGE_PIN C9 [get_ports {a_in[0]}]
set_property PACKAGE_PIN B9 [get_ports {a_in[1]}]
set_property PACKAGE_PIN G11 [get_ports {a_in[2]}]
set_property PACKAGE_PIN F10 [get_ports {a_in[3]}]
set_property PACKAGE_PIN D10 [get_ports {a_in[4]}]
set_property PACKAGE_PIN E11 [get_ports {a_in[5]}]
set_property PACKAGE_PIN D11 [get_ports {a_in[6]}]
set_property PACKAGE_PIN A14 [get_ports {a_in[7]}]

set_property PACKAGE_PIN B10 [get_ports {b_in[0]}]
set_property PACKAGE_PIN A10 [get_ports {b_in[1]}]
set_property PACKAGE_PIN B15 [get_ports {b_in[2]}]
set_property PACKAGE_PIN A15 [get_ports {b_in[3]}]
set_property PACKAGE_PIN A13 [get_ports {b_in[4]}]
set_property PACKAGE_PIN A12 [get_ports {b_in[5]}]
set_property PACKAGE_PIN D8  [get_ports {b_in[6]}]
set_property PACKAGE_PIN D9  [get_ports {b_in[7]}]

set_property PACKAGE_PIN F8 [get_ports {rst}]

set_property PACKAGE_PIN G16 [get_ports {sum_out[0]}]
set_property PACKAGE_PIN H16 [get_ports {sum_out[1]}]
set_property PACKAGE_PIN D16 [get_ports {sum_out[2]}]
set_property PACKAGE_PIN D15 [get_ports {sum_out[3]}]
set_property PACKAGE_PIN C18 [get_ports {sum_out[4]}]
set_property PACKAGE_PIN C17 [get_ports {sum_out[5]}]
set_property PACKAGE_PIN B19 [get_ports {sum_out[6]}]
set_property PACKAGE_PIN C19 [get_ports {sum_out[7]}]
set_property PACKAGE_PIN A17 [get_ports {sum_out[8]}]
set_property PACKAGE_PIN B17 [get_ports {sum_out[9]}]
set_property PACKAGE_PIN K20 [get_ports {sum_out[10]}]
set_property PACKAGE_PIN J20 [get_ports {sum_out[11]}]
set_property PACKAGE_PIN J18 [get_ports {sum_out[12]}]
set_property PACKAGE_PIN J19 [get_ports {sum_out[13]}]
set_property PACKAGE_PIN L19 [get_ports {sum_out[14]}]
set_property PACKAGE_PIN L20 [get_ports {sum_out[15]}]

set_property PACKAGE_PIN E10 [get_ports clk]
set_property IOSTANDARD LVCMOS18 [get_ports clk]


set_property IOSTANDARD LVCMOS18 [get_ports {a_in[0]}]
set_property IOSTANDARD LVCMOS18 [get_ports {a_in[1]}]
set_property IOSTANDARD LVCMOS18 [get_ports {a_in[2]}]
set_property IOSTANDARD LVCMOS18 [get_ports {a_in[3]}]
set_property IOSTANDARD LVCMOS18 [get_ports {a_in[4]}]
set_property IOSTANDARD LVCMOS18 [get_ports {a_in[5]}]
set_property IOSTANDARD LVCMOS18 [get_ports {a_in[6]}]
set_property IOSTANDARD LVCMOS18 [get_ports {a_in[7]}]

set_property IOSTANDARD LVCMOS18 [get_ports {b_in[0]}]
set_property IOSTANDARD LVCMOS18 [get_ports {b_in[1]}]
set_property IOSTANDARD LVCMOS18 [get_ports {b_in[2]}]
set_property IOSTANDARD LVCMOS18 [get_ports {b_in[3]}]
set_property IOSTANDARD LVCMOS18 [get_ports {b_in[4]}]
set_property IOSTANDARD LVCMOS18 [get_ports {b_in[5]}]
set_property IOSTANDARD LVCMOS18 [get_ports {b_in[6]}]
set_property IOSTANDARD LVCMOS18 [get_ports {b_in[7]}]

set_property IOSTANDARD LVCMOS18 [get_ports {rst}]

set_property IOSTANDARD LVCMOS18 G16 [get_ports {sum_out[0]}]
set_property IOSTANDARD LVCMOS18 H16 [get_ports {sum_out[1]}]
set_property IOSTANDARD LVCMOS18 D16 [get_ports {sum_out[2]}]
set_property IOSTANDARD LVCMOS18 D15 [get_ports {sum_out[3]}]
set_property IOSTANDARD LVCMOS18 C18 [get_ports {sum_out[4]}]
set_property IOSTANDARD LVCMOS18 C17 [get_ports {sum_out[5]}]
set_property IOSTANDARD LVCMOS18 B19 [get_ports {sum_out[6]}]
set_property IOSTANDARD LVCMOS18 C19 [get_ports {sum_out[7]}]
set_property IOSTANDARD LVCMOS18 A17 [get_ports {sum_out[8]}]
set_property IOSTANDARD LVCMOS18 B17 [get_ports {sum_out[9]}]
set_property IOSTANDARD LVCMOS18 K20 [get_ports {sum_out[10]}]
set_property IOSTANDARD LVCMOS18 J20 [get_ports {sum_out[11]}]
set_property IOSTANDARD LVCMOS18 J18 [get_ports {sum_out[12]}]
set_property IOSTANDARD LVCMOS18 J19 [get_ports {sum_out[13]}]
set_property IOSTANDARD LVCMOS18 L19 [get_ports {sum_out[14]}]
set_property IOSTANDARD LVCMOS18 L20 [get_ports {sum_out[15]}]

