set_property PACKAGE_PIN C9 [get_ports {datain[0]}]
set_property PACKAGE_PIN B9 [get_ports {datain[1]}]
set_property PACKAGE_PIN G11 [get_ports {datain[2]}]
set_property PACKAGE_PIN F10 [get_ports {datain[3]}]
set_property PACKAGE_PIN D10 [get_ports {datain[4]}]
set_property PACKAGE_PIN E11 [get_ports {datain[5]}]
set_property PACKAGE_PIN D11 [get_ports {datain[6]}]
set_property PACKAGE_PIN A14 [get_ports {datain[7]}]

set_property PACKAGE_PIN B10 [get_ports {rst}]
set_property PACKAGE_PIN A10 [get_ports {wr}]
set_property PACKAGE_PIN B15 [get_ports {rd}]

set_property PACKAGE_PIN G16 [get_ports {dataout[0]}]
set_property PACKAGE_PIN H16 [get_ports {dataout[1]}]
set_property PACKAGE_PIN D16 [get_ports {dataout[2]}]
set_property PACKAGE_PIN D15 [get_ports {dataout[3]}]
set_property PACKAGE_PIN C18 [get_ports {dataout[4]}]
set_property PACKAGE_PIN C17 [get_ports {dataout[5]}]
set_property PACKAGE_PIN B19 [get_ports {dataout[6]}]
set_property PACKAGE_PIN C19 [get_ports {dataout[7]}]

set_property PACKAGE_PIN A17 [get_ports {empty}]
set_property PACKAGE_PIN B17 [get_ports {full}]

set_property PACKAGE_PIN E10 [get_ports clk]
set_property IOSTANDARD LVCMOS18 [get_ports clk]

set_property IOSTANDARD LVCMOS18 [get_ports {datain[0]}]
set_property IOSTANDARD LVCMOS18 [get_ports {datain[1]}]
set_property IOSTANDARD LVCMOS18 [get_ports {datain[2]}]
set_property IOSTANDARD LVCMOS18 [get_ports {datain[3]}]
set_property IOSTANDARD LVCMOS18 [get_ports {datain[4]}]
set_property IOSTANDARD LVCMOS18 [get_ports {datain[5]}]
set_property IOSTANDARD LVCMOS18 [get_ports {datain[6]}]
set_property IOSTANDARD LVCMOS18 [get_ports {datain[7]}]
set_property IOSTANDARD LVCMOS18 [get_ports {rst}]
set_property IOSTANDARD LVCMOS18 [get_ports {wr}]
set_property IOSTANDARD LVCMOS18 [get_ports {rd}]
set_property IOSTANDARD LVCMOS18 [get_ports {dataout[0]}]
set_property IOSTANDARD LVCMOS18 [get_ports {dataout[1]}]
set_property IOSTANDARD LVCMOS18 [get_ports {dataout[2]}]
set_property IOSTANDARD LVCMOS18 [get_ports {dataout[3]}]
set_property IOSTANDARD LVCMOS18 [get_ports {dataout[4]}]
set_property IOSTANDARD LVCMOS18 [get_ports {dataout[5]}]
set_property IOSTANDARD LVCMOS18 [get_ports {dataout[6]}]
set_property IOSTANDARD LVCMOS18 [get_ports {dataout[7]}]

set_property IOSTANDARD LVCMOS18 [get_ports {empty}]
set_property IOSTANDARD LVCMOS18 [get_ports {full}]
